import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PageWrapper from "@/components/PageWrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white overflow-x-hidden`}>
        {/* Grainy Image Background */}
        <div className="fixed inset-0 pointer-events-none z-[-1]">
          {/* Background image with grain */}
          <div 
            className="absolute inset-0 bg-cover bg-center bg-no-repeat opacity-40"
            style={{
              backgroundImage: `url('/images/.jpg')`
            }}
          ></div>
          {/* Dark overlay to maintain readability */}
          <div className="absolute inset-0 bg-black/70"></div>
          {/* Purple accent */}
          <div className="absolute inset-0 bg-gradient-to-r from-transparent via-[#7736F8]/8 to-transparent"></div>
        </div>
        
        <Navbar/>
        <PageWrapper>
          {children}
        </PageWrapper>
        <Footer />
      </body>
    </html>
  );
}
